### ISSUE TITLE
`FetchEvent.respondWith` error in Safari

### ISSUE THREAD

**Issue by FredrikHillbert** [remix-pwa/sw#18]
I tried to run the service worker in Safari Version 16.1 (18614.2.9.1.12), but got an error.

The error is thrown by the handle function in the `NetworkFirst` class: 
```
   const cachedResponse = yield cache.match(request, this.matchOptions);
       if (cachedResponse) {
            cachedResponse.headers.set('X-Remix-Worker', 'yes'); // this line is producing the error.
             return cachedResponse;
        }
```

_How to reproduce:_ 
Run the service worker in Safari and then disconnect from the internet and reload the page. 

_Observed behaviour:_ 
Safari responds with the following error message: 

`FetchEvent.responseWith received an error: Headers object’s guard is TypeError ‘immutable’ (WebKitServiceWorker:0)`

_What should happen:_ 
The service worker should return the cached data as it does when running in Chrome.

If `cachedResponse.headers.set('X-Remix-Worker', 'yes');` is commented out, it's working as expected.

What is the purpose of setting the `cachedResponse.headers.set('X-Remix-Worker', 'yes')`, could this be removed?

**Comment by ShafSpecs** [comment]
> What is the purpose of setting the `cachedResponse.headers.set('X-Remix-Worker', 'yes')`, could this be removed?

Yes, it could be removed and your app works fine but it's to differentiate network response from service worker responses. If you aren't using plugins or anything that monitors usage, it's fine. But the moment you start integrating an analytics plugin or anything that needs cached responses and it becomes an issue. 

Ik a workaround though, not sure when I would implement as I am working on some guides for `@remix-pwa/push` but that is to create a whole new response altogether instead of mutating it. Something like:

```ts
const cachedResponse = cache.match(request, this.matchOptions);

const body = cachedResponse.clone().body;
const headers = new Headers(cachedResponse.clone().headers);

const newResponse = new Response(body, {
  headers: {...headers, 'X-Remix-Worker', 'yes')
  status: cachedResponse.status
  statusText = cachedResponse.statusText
})
```

Something similar to this logic, would you mind opening a PR please?

**Comment by haakonmt** [comment]
I believe this same issue is still present in `RemixLoaderPlugin`, which modifies the response headers directly in its `cachedResponseWillBeUsed` callback, causing this error in Safari:
`TypeError: Headers object's guard is 'immutable'`.

**Comment by ShafSpecs** [comment]
> I believe this same issue is still present in `RemixLoaderPlugin`, which modifies the response headers directly in its `cachedResponseWillBeUsed` callback, causing this error in Safari: `TypeError: Headers object's guard is 'immutable'`.

Very true https://github.com/remix-pwa/sw/blob/7ccddad1452b33d0f85524cd3ab078e8d484a81a/src/workbox/plugins/loaderPlugin.ts#L25

A fix for this would be out this weekend. Btw, `v2` is coming out next week 😁, and for now Workbox won't be supported (yet). I would try and fix this issue this weekend before then 👍

**Comment by ShafSpecs** [comment]
https://github.com/remix-pwa/sw/pull/27

Fix merged 👍
