### ISSUE TITLE
Intermittent typeError when trying to get the routes from manifest and they are not ready yet.

### ISSUE THREAD

**Issue by doctorDAlvarez** [remix-pwa/sw#2]
remix 1.14.3
remix-pwa/sw  0.1.1
react 18.2

I just finish setting up a remix app with v2 features and add pwa package. But noticed an intermittent typeError on precacheHandler.ts
on line 48-49: 
48    const manifest: AssetsManifest = event.data.manifest;
49    const routes = Object.values(manifest.routes);

Sometimes manifest has no reference yet, depending on network latency or on how fast root.tsx is render. Dont know exactly why is happening, I got 4 renders of root.tsx, maybe thats the issue. The PWA is working perfect just sometimes the service worker has this error. Is intermittent at least on my app.

I changed line 49 to
`const routes = Object.values(manifest?.routes || {})` and the error of course dissapear.

Let me know if I can submit a PR for this? I dont know to be honest.

Thanks sooo much for this package I love it. Anything I can do to help just let me know.

Love

Diego

<img width="1162" alt="Screenshot 2023-05-26 at 08 47 29" src="https://github.com/remix-pwa/sw/assets/66154743/4e32207d-db25-4377-b846-c7e9a57e0596">
<img width="1162" alt="Screenshot 2023-05-26 at 08 47 24" src="https://github.com/remix-pwa/sw/assets/66154743/cb708bd9-a102-454b-8322-2b235cec7652">

**Comment by ShafSpecs** [comment]
For sure! A PR would be very much appreciated. And yes, your solution would fit well. Because if the manifest hasn't loaded, there is no route information to load anyway

**Comment by ShafSpecs** [comment]
You can open a PR and link this issue, so it gets closed with its merge 👍

**Comment by ShafSpecs** [comment]
Would push a minor update in a few hours

**Comment by doctorDAlvarez** [comment]
@ShafSpecs I am so sory I had some internet issues and totally missed this notifications. I am super glad that its already merged. Let me know if I can collaborate with your team or have any issues you want me to help with. I will love to participate in this super usefull project. Thanks so much! 
Diego

**Comment by ShafSpecs** [comment]
> @ShafSpecs I am so sory I had some internet issues and totally missed this notifications. I am super glad that its already merged. Let me know if I can collaborate with your team or have any issues you want me to help with. I will love to participate in this super usefull project. Thanks so much! 
> Diego

Thanks a bunch. With regards to issues, currently because the packages are in pre-v1 stage, there isn't much of a roadmap yet for implementing features. But if you have an idea and want to share it in an issue, that would be great. Or resolve the few issues that are open 😊
