### ISSUE TITLE
Something is very wrong with response headers

### ISSUE THREAD

**Issue by ShafSpecs** [remix-pwa/sw#4]
Whilst building out the expiration plugin, I found that remix-pwa custom headers wasn't showing up in the browser. I also tested it out with multiple template apps, none of them seemed to work. 

My current thought is that the headers weren't modified before being returned (which is quite wrong) or I am not inspecting the response enough. Since expiration plugin (and a lot more plugins in mind) relies on headers present, I want to make this a priority.

**Comment by dev-afzalansari** [comment]
I think this one is solved now.
