### ISSUE TITLE
`sw` package causes entire app to crash

### ISSUE THREAD

**Issue by ShafSpecs** [remix-pwa/sw#9]
<img width="577" alt="image" src="https://github.com/remix-pwa/sw/assets/69679506/bb2b37cc-04ca-4a0b-b665-c82b19708ebe">

Get this message anytime I load the new `v0.3.0` version.

**Comment by ShafSpecs** [comment]
Seems to have broken since v0.2.1

**Comment by ShafSpecs** [comment]
build scripts broke the package. Look at that later

**Comment by dev-afzalansari** [comment]
Will look at it tomorrow.
